config/routes.rb
SearchEngine::Application.routes.draw do
  get "search/index"
  get "dictionary/index"
  get "page/show(/:id)" => "page#show"
  root :to => 'search#index'

end

app/models/dictionary.rb
class Dictionary
  include MongoMapper::Document
  plugin MongoMapper::Plugins::IdentityMap

  key :term, String
  key :doc_count, Integer
  key :tot_freq, Integer
  key :idf, Float

  timestamps!

  many :postings

  def self.initialize_cache
    Dictionary.all.each do |dict|
      Rails.cache.write(dict.term, [dict.term, dict.doc_count, dict.tot_freq, dict.idf ],
                        {:unless_exists => true})
    end
  end
end

app/models/page.rb
# REMEMBER TO UPDATE ./mapreduce/crawler.rb definition if you
# change this substantially
class Page
  include MongoMapper::Document
  plugin MongoMapper::Plugins::IdentityMap

  # Included for excerpt function
  include ActionView::Helpers::TextHelper

  key :docid, String
  key :name, String
  key :url, String
  key :visited, Boolean
  key :last_visited, Date
  key :last_visited_status_code
  key :html, String
  key :indexed, Boolean

  key :vector_length, Float

  timestamps!

  many :postings

  # Returns all models where visited is not true
  def self.not_visited
    Page.all(:visited => [false, nil])
  end

  def self.not_indexed
    Page.where(:indexed => [false, nil], :visited => true).fields(:docid)
  end

  def get_excerpts(phrase, *args)
    terms = phrase.split(' ')

    doc = Hpricot(self.html)
    doc.search('head').remove
    doc.search('script').remove
    doc.search('style').remove
    doc.search('iframe').remove
    doc.search('embed').remove

    snippets = []
    nodes =  (doc/"body//*/text()")
    # Delete all empty nodes
    nodes = nodes.delete_if {|node| node.to_s.strip.blank?}

    # Find the excerpt
    nodes.each do |node|
      text = node.to_plain_text.chomp.strip
      terms.each do |term|
        regex = Regexp.new(term, Regexp::IGNORECASE )
        if regex =~ text
          snippets << excerpt(text, term, *args)
        else
          logger.warn "NO MATCH on #{term}!!!"
          logger.warn text
          logger.warn "~~~~~~~~~~~~"
        end
      end
    end
    results = snippets.uniq
    logger.info "Found #{results.size} excerpts"
    results
  end
end

app/models/posting.rb
class Posting
  include MongoMapper::Document
  plugin MongoMapper::Plugins::IdentityMap

  key :term, String
  key :docid, String
  key :freq, Integer
  key :locations, String
  key :tfidf, Float
  key :weight, Float
  key :excerpts, Array

  timestamps!

  belongs_to :dictionary
  belongs_to :page
end

app/models/query.rb
class Query
  attr_accessor :postings

  # Algorithm from implementation.ppt slide 18
  def process(raw_query_terms)
    terms = analyze_terms(raw_query_terms) 

    q = [] # hold query term weights
    r = {} # stores retrieved documents and scores

    terms.each do |term|
      t = Rails.cache.read(term)
      next if t.nil? # This term is not in the dictionary

      term_idf = t[3]  # IDF of T (dictionary.idf)
      k = 1            # Count of T in Q
      w = k * term_idf # weight of query term (tf x idf)
      q << w           # save the weight for later

      # Compute posting tf x idf
      @postings = Posting.where(:term => term)
      @postings.each do |posting|
        d = posting.docid
        c = posting.freq # term frequency of T in D
        if r.has_key?(d)
          r[d] += w * term_idf * c  # (dot product)
          # Should be same as posting tfidf
        else
          r[d] = w * term_idf * c
        end
      end
    end

    # Compute the norm of the query terms
    l = compute_vector_length(q)

    scores = compute_cosine_similarity(r, l)

    # Sort in descending order by score
    result = scores.sort {|a1, a2| a2[1] <=> a1[1]}
  end

  private

  # Split the terms and send to 
  # InvertedIndex Cleaner to remove
  # stop words and stem the terms
  def analyze_terms(raw_query_terms)
    # Split into terms
    query_terms = raw_query_terms.split(' ')

    # Perform Lexical Analysis
    InvertedIndex::Cleaner.clean(query_terms)
  end

  # Compute the cosine similarity
  def compute_cosine_similarity(r, l)
    scores = {}
    r.each do |docid, score|
      y = Page.where(:docid => docid).fields(:vector_length).first.vector_length
      # Cosine similarity
      scores[docid] = score.to_f / (l * y).to_f
    end
    scores
  end

  # Square root of sum of squares
  def compute_vector_length(vector)
    # Sum of squares
    sum = 0
    vector.each {|v| sum += v ** 2}
    # Take square root
    Math.sqrt(sum)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @alpha = params[:alpha] || 'a'
    regex = Regexp.new("^#{@alpha}", Regexp::IGNORECASE)
    @terms = Dictionary.paginate(:term => regex, :page => params[:page], :per_page => 100)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dictionary_controller.rb
class DictionaryController < ApplicationController
  def index
    @alpha = params[:alpha] || 'a'
    regex = Regexp.new("^#{@alpha}", Regexp::IGNORECASE)
    @terms = Dictionary.paginate(:term => regex, :page => params[:page], :per_page => 100)
  end
end

app/controllers/page_controller.rb
class HtmlStub
  attr_accessor :text, :html
end

class PageController < ApplicationController
  def show
    @page = Page.first(:docid => params[:id]) if params[:id]
    parser = InvertedIndex::Parse.new(@page.html)
    text = parser.parse
    @html = HtmlStub.new
    @html.text = text
    @html.html = parser.doc.html
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    # is a query present?
    if params[:q]
      @q = params[:q]
      @query = Query.new

      # Parse the query
      @ranked_results = @query.process(@q)

      # Group results by posting
      @postings = @query.postings.group_by {|posting| posting.docid} if @ranked_results.present?

      # Set the search result message
      @message = (@ranked_results.present?) ? "Search results for #{@q}" : "No results found for #{@q}"
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
  def alpha_links(action)
    links  = []
    # Create index for 0 through 9
    (0..9).to_a.each do |number|
      links << "<span>" + link_to(number, :action => action, :alpha => number) + "</span>"
    end
    # Create index for A through Z
    ('A'..'Z').to_a.each do |letter|
      links << "<span>" + link_to(letter, :action => action, :alpha => letter) + "</span>"
    end
    raw links.join('|')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dictionary_helper.rb
module DictionaryHelper
  def alpha_links(action)
    links  = []
    # Create index for 0 through 9
    (0..9).to_a.each do |number|
      links << "<span>" + link_to(number, :action => action, :alpha => number) + "</span>"
    end
    # Create index for A through Z
    ('A'..'Z').to_a.each do |letter|
      links << "<span>" + link_to(letter, :action => action, :alpha => letter) + "</span>"
    end
    raw links.join('|')
  end
end

app/helpers/search_helper.rb
module SearchHelper
  def get_excerpt(docid, postings)
    excerpts = []
    begin
      count = 0
      postings[docid].each do |posting|
        posting.excerpts.each do |exc|
          excerpts << highlight(exc, posting.term)
          count += 1
          # Only include 3 excerpts
          break if count > 3
        end
      end
    rescue Exception => ex
      logger.error "~~~~~ get_excerpt (#{docid})"
      logger.error ex.message
    end

    excerpts.blank? ? "No excerpts for this term" : excerpts.join(" ... ")
  end
end

app/views/dictionary/index.html.erb
<div class="row">
  <div class="span12">
    <h2>Dictionary Terms for <%= @alpha %></h2>

    <div class = "alpha">
      <%= alpha_links('index') %>
    </div>
  </div>
</div>

<div class="row">
  <div class="span12">
    <%= will_paginate @terms %>
  </div>
</div>

<div class="row">
  <div class="span12">
    <% @terms.each do |dict| %>
      <div class="well span2">
        <dt><span><%= dict.term %><span></dt>
          <dd>Doc count: <%= dict.doc_count %></dd>
          <dd>Total freq: <%= dict.tot_freq %></dd>
          <dd>IDF: <%= sprintf "%3.3f", dict.idf %></dd>
        </dl>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="span12">
    <%= will_paginate @terms %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>/Search/</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Search", root_url, :class => 'brand' %>
          <div class="container nav-collapse">
            <ul class="nav">
                <li><%= link_to "Dictionary", dictionary_index_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <%= yield %>
      </div><!--/content-->
    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/page/show.html.erb
<div class="row">
  <div class="span12">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#text" data-toggle="tab">Text</a></li>
      <li><a href="#html" data-toggle="tab">HTML</a></li>
      <li><a href="#cache" data-toggle="tab">Cache</a></li>
    </ul>

    <div class="tab-content">
      <div class="tab-pane active" id="text">
        <pre>
          <%= @html.text %>
        </pre>
      </div>
      <div class="tab-pane" id="html">
        <pre>
          <%= @html.html.strip %>
        </pre>
      </div>
      <div class="tab-pane" id="cache">
        <p>This has no javascript or stylesheets</p>
        <%= raw @html.html.strip %>
      </div>
    </div>
  </div>
</div>

app/views/search/_results.html.erb
<% if results.present? %>
  <div class="span12">
    <ol>
      <% results.each do |result| %>
        <% docid = result[0] %>
        <% score = result[1] %>
        <% page = Page.first(:docid => docid) %>
        <li>
          <div>
            <h3><%= link_to page.name, page.url %></h3>
          </div>
          <div>
            <div>
              <cite><%= page.url %></cite>
            </div>
            <span><%= raw get_excerpt(docid, @postings) %>
            </span>
            <div class="alert alert-info">
              <span>Score: <%= sprintf("%3.3f", score) %></span> |
              <span>Docid:  <%= link_to docid, {:controller => 'page', :action => 'show', :id => docid}, {:target => "_blank"} %></span>
            </div>
          </div>
        </li>
      <% end %>
    </ol>
  </div>
<% end %>

app/views/search/_search_form.html.erb
<div class="span12">
  <%= form_tag search_index_path, :method => "get", :class => 'well form-search', :remote => true do %>
    <%= label_tag :q, "Search for :" %>
    <%= text_field_tag :q, q, :size => 55, :maxlength => 2048, :class => 'input-super-large search-query'  %>
    <%= button_tag " Search", :class => 'btn btn-primary' do  %>
      <i class="icon-search icon-white"></i> Search
    <% end %>
  <% end %>
</div>

app/views/search/_search_results_message.html.erb
<div class="span12">
  <h2><%= message %></h2>
  <% if @ranked_results.present? %>
  <span>
    <%= check_box_tag 'debug_checkbox', 'checked', true %> Show ranking information
  </span
<% end %>
</div>

<% if @ranked_results.present? %>
  <script type="text/javascript">
    $("#debug_checkbox").click(function() {
        $(".alert").toggle();
    });
  </script>
<% end %>

app/views/search/index.html.erb
<div class="row">
  <%= render :partial => 'search_form', :locals => {:q => @q} %>
</div><!--/row-->

<div class="row" id="search_results_message">
  <%= render :partial => 'search_results_message', :locals => {:message => @message} if @message %>
</div><!--/row-->

<div class="row" id="ranked_results">
  <%= render :partial => 'results', :locals => {:results => @ranked_results} if @ranked_results.present? %>
</div><!--/row-->

app/views/search/index.js.erb
$("#search_results_message").html("<%= escape_javascript(render :partial => 'search_results_message', :locals => {:message => @message}) %>")

$("#ranked_results").html("<%= escape_javascript(render :partial => 'results', :locals => {:results => @ranked_results}) %>")

$("#q").focus()